RestNoteBook/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework_simplejwt.views import *

from RestNoteBook import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restbook.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_refresh'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restbook/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home"),
    path('addnote', AddNoteView.as_view(),  name='addnote'),
    path('profile/', profile, name='profile'),
    path('visit/<slug:slug>/', visit, name='visit'),
    path('leave_comment/', leave_comment, name='leave_comment'),
    path('edit/<slug:slug>/', edit, name='edit'),
    path('delete/<slug:slug>/', delete_post, name='delete'),


]

users/urls.py
from django.urls import path

from .views import *

app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    #path('register/', register, name='register'),
    path('register/api/', Register.as_view(), name='register'),
    ]

restbook/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from RestNoteBook import settings


class Rest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,)
    slug = models.SlugField(unique=True, default=uuid.uuid1)
    restaurant_name = models.CharField(max_length=50)
    cuisine = models.CharField(max_length=50)
    notes = models.TextField(blank=True)
    images = models.FileField(upload_to='images/',)
    time_created = models.DateTimeField(auto_now_add=True)
    time_updated = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.restaurant_name

    def get_absolute_url(self):
        return reverse('visit', kwargs={'slug': self.slug})



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=250, unique=True, db_index=True)
    avatar = models.ImageField(null=True, upload_to='profile_images')
    bio = models.TextField()

    def __str__(self):
        return self.user.username




class ReviewModel(models.Model):
    notes = models.TextField(max_length=300)
    price = models.FloatField()
    date = models.DateField()


    def __str__(self):
        return self.notes

restbook/forms.py
from django import forms
from .models import *
from .models import Rest

class AddForm(forms.ModelForm):
    class Meta:
        model = Rest
        fields = [ 'restaurant_name', 'cuisine', 'notes', 'images', 'is_published']


class ReviewForm(forms.ModelForm):

    class Meta:
        model = ReviewModel
        fields = ['notes', 'price', 'date']

restbook/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.files import images
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import *
from .forms import *
from .urls import *

def home(request):
    rest = Rest.objects.filter(is_published=1)
    title = {'title': "Home"}
    return render(request, 'restbook/articles.html', {'rest': rest, 'title': title})

def articles(requst):
    pass


class AddNoteView(LoginRequiredMixin, CreateView):
    model = Rest
    form_class = AddForm
    template_name = 'restbook/addnote.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


@login_required
def edit(request, slug):
    model = get_object_or_404(Rest, slug=slug)
    if request.user != model.user:
        # Redirect or show an error message indicating the user doesn't have permission
        return render(request, 'restbook/exceptions.html')

    form = AddForm(instance=model)

    if request.method == 'POST':
        form = AddForm(request.POST, instance=model)
        if form.is_valid():
            form.save()
            return redirect('home')
    return render(request, 'restbook/updatenote.html', {'form': form})

@login_required
def delete_post(request, slug):
    model = get_object_or_404(Rest, slug=slug)
    if request.user != model.user:
        # Redirect or show an error message indicating the user doesn't have permission
        return render(request, 'restbook/exceptions.html')

    if request.method == 'GET':
        return render(request, 'restbook/delete.html', {'model': model})

    elif request.method == 'POST':
        model.delete()
        return redirect('home')



@login_required()
def profile(request):
    prof = Profile.objects.get(user=request.user)
    title = {'title': "Profiles"}
    return render(request, 'restbook/profile.html', {'prof': prof})



def visit(request, slug):
    post = get_object_or_404(Rest, slug=slug)
    review = ReviewModel.objects.all()

    return render(request, 'restbook/visit.html', {'post': post, 'review': review})
@login_required()
def leave_comment(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = ReviewForm()
    return render(request, 'restbook/leave_comment.html', {'form': form})

restbook/templates/restbook/addnote.html
{% extends 'restbook/main.html' %}
{% load static %}

{% block content%}
      <form method="post" enctype="multipart/form-data">>
          <main class="form-signin">
              <h1 class="h3">Login</h1>
                {% csrf_token %}
                <div class="form-floating">
                    {{ form.as_p }}
                </div>
                <p><button classs='"w-100 btn btn-lg' type="submit">Register</button></p>
    </form>


{% endblock %}

restbook/templates/restbook/articles.html
{% extends 'restbook/main.html' %}
{% load static %}



{% block content %}
{% for rest in rest %}
        {% if rest.images %}
        <a href="{% url 'visit' slug=rest.slug %}" class="post-home">
            <div class="home-card">
                <h1><em>{{ rest.restaurant_name }}</em></h1>
                <p>{{ rest.cuisine }}</p>
                <p><{{ rest.user }}</p>
                <img class="image" src="{{ rest.images.url }}">
                <p>{{ rest.user }}</p>
            {% if user.is_authenticated %}
                <a href="{% url 'edit' slug=rest.slug %}">Edit</a>
                <form method="post">{% csrf_token %}
                <a href="{% url 'delete' slug=rest.slug %}">Delete</a>


</form>
            {% endif %}
            </div>

         </a>
        {% endif %}

{% endfor %}

{% endblock %}

restbook/templates/restbook/delete.html
{% extends 'restbook/main.html' %}
{% load static %}

{% block content%}
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endblock %}

restbook/templates/restbook/exceptions.html
{% extends 'restbook/main.html' %}
{% load static %}

{% block content%}
    <div class="home-card">
        <p>You cannot edit or delete posts added by another user!</p>
    </div>
{% endblock %}

restbook/templates/restbook/home.html
{% extends 'restbook/main.html' %}
{% load static %}

{% block content %}

{% endblock %}

restbook/templates/restbook/main.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  		<title>{{ title }}</title>

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" href="{% static 'restbook/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'restbook/css/home.css' %}">
        <link rel="stylesheet" href="{% static 'restbook/css/profile.css' %}">
        <link rel="stylesheet" href="{% static 'restbook/css/forms.css' %}">
        <link rel="stylesheet" href="{% static 'restbook/css/loginform.css' %}">


        <link href="https://fonts.googleapis.com/css?family=Kanit:100,200,300,400,500,600,700,800,900" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@100&family=Nunito:ital,wght@0,200..1000;1,200..1000&family=Roboto:wght@100;400&display=swap" rel="stylesheet">



        <script src="js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    </head>

<body>

<div class="header">
    <div class="box">
        <a href="{% url 'home' %}" class="menu">home</a>

        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}" class="menu">Profile</a>
            <a href="{% url 'addnote' %}" class="menu">Add Note</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}" class="menu">Logout</a>
        {% else %}
            <a href="{% url 'users:login' %}" class="menu">Login</a> | <a href="{% url 'users:register' %}" class="menu">Registraion</a>
        {% endif %}

    </div>
</div>

<div class="main">
    <div class="box">
        {% block content %}
        {% endblock %}
    </div>

</div>




</body>
</html>

restbook/templates/restbook/profile.html
{% extends 'restbook/main.html' %}
{% load static %}

{% block content %}
    <div class="profile-block">

        <div class="card">
            <img src="{{ prof.avatar.url }}" style="width:100%">
            <h1>{{ prof.user }}</h1>
            <p class="title">{{ prof.bio }}</p>
            <p class="fa fa-dribbble">{{ prof.bio }}</p>

        </div>


    </div>

{% endblock %}

restbook/templates/restbook/updatenote.html
{% extends 'restbook/main.html' %}
{% load static %}

{% block content%}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

restbook/templates/restbook/visit.html
{% extends 'restbook/main.html' %}
{% load static %}

{% block content %}
        {% if post.images %}
        <a class="post">
            <div class="home-card">
                <h1><em>{{ post.restaurant_name }}</em></h1>
                <p>{{ post.cuisine }}</p>
                <p><{{ post.user }}</p>
                <img class="image" src="{{ post.images.url }}">
                <p>{{ post.user }}</p>
            </div>
            <p class="card-note">{{ post.notes }}</p>
         </a>

        {% endif %}
    {% if user.is_authenticated %}

        <a class="leave_comment" href="{% url 'leave_comment' %}">Leave your comment</a>
    {% endif %}

        {% for review in review %}
            <div class="home-card">
                <p class="note">Note: {{ review.notes }}</p>
                <p class="price">Price: <{{ review.price }} $</p>
                <p class="price">Date of visit: {{ review.date }}</p>
            </div>
        {% endfor %}
{% endblock %}